name: Epic issues for GitHub
description: Automatically update task list when referenced issue is closed
inputs:
  github-token:
    description: GitHub token secret
    required: true
  epic-label-name:
    description: Label name for epic issues
    required: true
    default: epic
  auto-close-epic:
    description: Auto close epic when all referenced issues are closed
    required: false
    default: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: bookmark
  color: purple
